### ISSUE TITLE
Fix dark mode

### ISSUE THREAD

**Issue by lassa97** [lassa97/lassa97.github.io#1]
- [ ] Use `prefers-color-scheme` variable.
- [ ] Remove neon animations on light mode.

[A complete guide to dark mode on the Web](https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/)
[How to create neon text with CSS](https://css-tricks.com/how-to-create-neon-text-with-css/)

**Comment by lassa97** [comment]
```css
.neon-text {
    animation: flicker-text 0.11s ease-in-out 20 alternate
}

.neon-avatar {
    animation: flicker-avatar 2s 1 alternate;
}
```
